{
 "title": "System",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(system_cpu_user{source_id=\"bosh-system-metrics-forwarder\"}, deployment)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(system_cpu_user{source_id=\"bosh-system-metrics-forwarder\", deployment=~\"$deployment\"}, exported_job)"
   },
   {
    "name": "index",
    "label": "Index",
    "query": "label_values(system_cpu_user{source_id=\"bosh-system-metrics-forwarder\", deployment=\"$deployment\", exported_job=~\"$job\"}, index)"
   }
  ]
 },
 "panels": [
  {
   "title": "Jobs Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(system_healthy{deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"})"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_mem_percent{origin=\"bosh-system-metrics-forwarder\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Swap Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_swap_percent{origin=\"bosh-system-metrics-forwarder\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "CPU (user) Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{origin=\"bosh-system-metrics-forwarder\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "CPU (user) Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_user{origin=\"bosh-system-metrics-forwarder\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "CPU (wait) Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_wait{origin=\"bosh-system-metrics-forwarder\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Load Average (1m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_1m{origin=\"bosh-system-metrics-forwarder\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Load Average (5m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_5m{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Load Average (15m)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_15m{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "System Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_disk_system_percent{origin=\"bosh-system-metrics-forwarder\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Ephemeral Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_disk_ephemeral_percent{origin=\"bosh-system-metrics-forwarder\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Persistent Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_disk_persistent_percent{origin=\"bosh-system-metrics-forwarder\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}",
     "legendFormat": "{{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(system_network_bytes_sent{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}[5m])",
     "legendFormat": "{{network_interface}}: {{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(system_network_bytes_received{origin=\"system_metrics_agent\", deployment=~\"$deployment\", exported_job=~\"$job\", index=~\"$index\"}[5m])",
     "legendFormat": "{{network_interface}}: {{deployment}}/{{exported_job}}/{{index}}"
    }
   ]
  }
 ]
}