{
 "title": "Diego",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(total_requests{source_id=\"gorouter\"}, deployment)"
   }
  ]
 },
 "panels": [
  { "title": "Rep", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Diego Cell - Remaining Memory Available - Overall Remaining Memory Available",
   "type": "graph",
   "description": "Remaining amount of memory in MiB available for this Diego cell to allocate to containers.\n\nUse: Can indicate low memory capacity overall in the platform. Low memory can prevent app scaling and new deployments. The overall sum of capacity can indicate that you need to scale the platform. Observing capacity consumption trends over time helps with capacity planning.\n\nOrigin: Firehose\nType: Gauge (Integer in MiB)\nFrequency: 60 s",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "min_over_time(CapacityRemainingMemory{source_id=\"rep\", deployment=~\"$deployment\"}[5m]) / 1024",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Diego Cell - Remaining Disk Available - Overall Remaining Disk Available",
   "type": "graph",
   "description": "Remaining amount of disk in MiB available for this Diego cell to allocate to containers.\n\nUse: Low disk capacity can prevent app scaling and new deployments. Because Diego staging Tasks can fail without at least 6 GB free, the recommended red threshold is based on the minimum disk capacity across the deployment falling below 6 GB in the previous 5 minutes.\n\nIt can also be meaningful to assess how many chunks of free disk space are above a given threshold, similar to rep.CapacityRemainingMemory.\n\nOrigin: Firehose\nType: Gauge (Integer in MiB)\nFrequency: 60 s",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "min_over_time(CapacityRemainingDisk{source_id=\"rep\", deployment=~\"$deployment\"}[5m]) / 1024",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Diego Cell - Garden Healthcheck Failed",
   "type": "graph",
   "description": "The Diego cell periodically checks its health against the garden backend. For Diego cells, 0 means healthy, and 1 means unhealthy.\n\nUse: Set an alert for further investigation if multiple unhealthy Diego cells are detected in the given time window. If one cell is impacted, it does not participate in auctions, but end-user impact is usually low. If multiple cells are impacted, this can indicate a larger problem with Diego, and should be considered a more critical investigation need.\n\nSuggested alert threshold based on multiple unhealthy cells in the given time window.\n\nAlthough end-user impact is usually low if only one cell is impacted, this should still be investigated. Particularly in a lower capacity environment, this situation could result in negative end-user impact if left unresolved.\n\nOrigin: Firehose\nType: Gauge (Float, 0-1)\nFrequency: 30 s",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(GardenHealthCheckFailed{source_id=\"rep\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Diego Cell - Time to Sync",
   "type": "graph",
   "description": "Time in ns that the Diego Cell Rep took to sync the ActualLRPs that it claimed with its actual garden containers.\n\nUse: Sync times that are too high can indicate issues with the BBS.\n\nOrigin: Firehose\nType: Gauge (Float in ns)\nFrequency: 30 s",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(RepBulkSyncDuration{source_id=\"rep\", deployment=~\"$deployment\"}[15m]) / 1000000000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  { "title": "BBS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "BBS - Time to Run LRP Convergence",
   "type": "graph",
   "description": "Time in ns that the BBS took to run its LRP convergence pass.\n\nUse: If the convergence run begins taking too long, apps or Tasks may be crashing without restarting. This symptom can also indicate loss of connectivity to the BBS database.\n\nOrigin: Firehose\nType: Gauge (Integer in ns)\nFrequency: 30 s",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(ConvergenceLRPDuration{source_id=\"bbs\", deployment=~\"$deployment\"}[15m]) / 1000000000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "BBS - Time to Handle Requests",
   "type": "graph",
   "description": "The maximum observed latency time over the past 60 seconds that the BBS took to handle requests across all its API endpoints.\n\nDiego is now aggregating this metric to emit the max value observed over 60 seconds.\n\nUse: If this metric rises, the BBS API is slowing. Response to certain operations is slow if request latency is high.\n\nOrigin: Firehose\nType: Gauge (Integer in ns)\nFrequency: 60 s",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(RequestLatency{source_id=\"bbs\", deployment=~\"$deployment\"}[15m]) / 1000000000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "BBS - More App Instances Than Expected",
   "type": "graph",
   "description": "Total number of LRP instances that are no longer desired but still have a BBS record. When Diego wants to add more apps, the BBS sends a request to the auctioneer to spin up additional LRPs. LRPsExtra is the total number of LRP instances that are no longer desired but still have a BBS record.\n\nUse: If Diego has more LRPs running than expected, there may be problems with the BBS.\n\nDeleting an app with many instances can temporarily spike this metric. However, a sustained spike in bbs.LRPsExtra is unusual and should be investigated.\n\nOrigin: Firehose\nType: Gauge (Float)\nFrequency: 30 s",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(LRPsExtra{source_id=\"bbs\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "BBS - Fewer App Instances Than Expected",
   "type": "graph",
   "description": "Total number of LRP instances that are desired but have no record in the BBS. When Diego wants to add more apps, the BBS sends a request to the auctioneer to spin up additional LRPs. LRPsMissing is the total number of LRP instances that are desired but have no BBS record.\n\nUse: If Diego has less LRP running than expected, there may be problems with the BBS.\n\nAn app push with many instances can temporarily spike this metric. However, a sustained spike in bbs.LRPsMissing is unusual and should be investigated.\n\nOrigin: Firehose\nType: Gauge (Float)\nFrequency: 30 s",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(LRPsMissing{source_id=\"bbs\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "BBS - Crashed App Instances",
   "type": "graph",
   "description": "Total number of LRP instances that have crashed.\n\nUse: Indicates how many instances in the deployment are in a crashed state. An increase in bbs.CrashedActualLRPs can indicate several problems, from a bad app with many instances associated, to a platform issue that is resulting in app crashes. Use this metric to help create a baseline for your deployment. After you have a baseline, you can create a deployment-specific alert to notify of a spike in crashes above the trend line. Tune alert values to your deployment.\n\nOrigin: Firehose\nType: Gauge (Float)\nFrequency: 30 s",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(CrashedActualLRPs{source_id=\"bbs\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "BBS - Running App Instances, Rate of Change",
   "type": "graph",
   "description": "Rate of change in app instances being started or stopped on the platform. It is derived from bbs.LRPsRunning and represents the total number of LRP instances that are running on Diego cells.\n\nUse: Delta reflects upward or downward trend for app instances started or stopped. Helps to provide a picture of the overall growth trend of the environment for capacity planning. You may want to alert on delta values outside of the expected range.\n\nOrigin: Firehose\nType: Gauge (Float)\nFrequency: During event, emission should be constant on a running deployment.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(LRPsRunning{source_id=\"bbs\", deployment=~\"$deployment\"}[1h]) - avg_over_time(LRPsRunning{source_id=\"bbs\"}[1h]  offset 1h)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "BBS - Lock Held",
   "type": "graph",
   "description": "Whether a BBS instance holds the expected BBS lock (in Locket). 1 means the active BBS server holds the lock, and 0 means the lock was lost.\n\nUse: This metric is complimentary to Active Locks, and it offers a BBS-level version of the Locket metrics. Although it is emitted per BBS instance, only 1 active lock is held by BBS. Therefore, the expected value is 1. The metric may occasionally be 0 when the BBS instances are performing a leader transition, but a prolonged value of 0 indicates an issue with BBS.\n\nOrigin: Firehose\nType: Gauge\nFrequency: Periodically",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(LockHeld{source_id=\"bbs\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "BBS - Cloud Controller and Diego in Sync",
   "type": "graph",
   "description": "Indicates if the cf-apps Domain is up-to-date, meaning that CF App requests from Cloud Controller are synchronized to bbs.LRPsDesired (Diego-desired AIs) for execution.\n- 1 means cf-apps Domain is up-to-date\n- No data received means cf-apps Domain is not up-to-date\n\nUse: If the cf-apps Domain does not stay up-to-date, changes requested in the Cloud Controller are not guaranteed to propagate throughout the system. If the Cloud Controller and Diego are out of sync, then apps running could vary from those desired.\n\nOrigin: Firehose\nType: Gauge (Float)\nFrequency: 30 s",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(Domain_cf_apps{source_id=\"bbs\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  { "title": "Auctioneer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Auctioneer - App Instance (AI) Placement Failures",
   "type": "graph",
   "description": "The number of Long Running Process (LRP) instances that the auctioneer failed to place on Diego cells. This metric is cumulative over the lifetime of the auctioneer job.\n\nUse: This metric can indicate that Diego is out of container space or that there is a lack of resources within your environment. This indicator also increases when the LRP is requesting an isolation segment, volume drivers, or a stack that is unavailable, either not deployed or lacking sufficient resources to accept the work.\n\nThis metric is emitted on event, and therefore gaps in receipt of this metric can be normal during periods of no app instances being scheduled.\n\nThis error is most common due to capacity issues, for example, if cells do not have enough resources, or if cells are going back and forth between a healthy and unhealthy state.\n\nOrigin: Firehose\nType: Counter (Integer)\nFrequency: During each auction",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(AuctioneerLRPAuctionsFailed{source_id=\"auctioneer\", deployment=~\"$deployment\"}[5m]) * 60",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Auctioneer - Time to Fetch Cell State",
   "type": "graph",
   "description": "Time in ns that the auctioneer took to fetch state from all the Diego cells when running its auction.\n\nUse: Indicates how the cells themselves are performing. Alerting on this metric helps alert that app staging requests to Diego may be failing.\n\nOrigin: Firehose\nType: Gauge, integer in ns\nFrequency: During event, during each auction",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(AuctioneerFetchStatesDuration{source_id=\"auctioneer\", deployment=~\"$deployment\"}[5m]) / 1000000000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Auctioneer - App Instance Starts",
   "type": "graph",
   "description": "The number of LRP instances that the auctioneer successfully placed on Diego cells. This metric is cumulative over the lifetime of the auctioneer job.\n\nUse: Provides a sense of running system activity levels in your environment. Can also give you a sense of how many app instances have been started over time. The provided measurement can help indicate a significant amount of container churn. However, for capacity planning purposes, it is more helpful to observe deltas over a long time window.\n\nThis metric is emitted on event, and therefore gaps in receipt of this metric can be normal during periods of no app instances being scheduled.\n\nOrigin: Firehose\nType: Counter (Integer)\nFrequency: During event, during each auction",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(AuctioneerLRPAuctionsStarted{source_id=\"auctioneer\", deployment=~\"$deployment\"}[5m]) * 60",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Auctioneer - Lock Held",
   "type": "graph",
   "description": "Whether an Auctioneer instance holds the expected Auctioneer lock (in Locket). 1 means the active Auctioneer holds the lock, and 0 means the lock was lost.\n\nUse: This metric is complimentary to Active Locks, and it offers an Auctioneer-level version of the Locket metrics. Although it is emitted per Auctioneer instance, only 1 active lock is held by Auctioneer. Therefore, the expected value is 1. The metric may occasionally be 0 when the Auctioneer instances are performing a leader transition, but a prolonged value of 0 indicates an issue with Auctioneer.\n\nOrigin: Firehose\nType: Gauge\nFrequency: Periodically",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(LockHeld{source_id=\"auctioneer\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Auctioneer - Task Placement Failures",
   "type": "graph",
   "description": "The number of Tasks that the auctioneer failed to place on Diego cells. This metric is cumulative over the lifetime of the auctioneer job.\n\nUse: Failing Task auctions indicate a lack of resources within your environment and that you likely need to scale. This indicator also increases when the Task is requesting an isolation segment, volume drivers, or a stack that is unavailable, either not deployed or lacking sufficient resources to accept the work.\n\nThis metric is emitted on event, and therefore gaps in receipt of this metric can be normal during periods of no tasks being scheduled.\n\nThis error is most common due to capacity issues, for example, if cells do not have enough resources, or if cells are going back and forth between a healthy and unhealthy state.\n\nOrigin: Firehose\nType: Counter (Float)\nFrequency: During event, during each auction",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(AuctioneerTaskAuctionsFailed{source_id=\"auctioneer\", deployment=~\"$deployment\"}[5m]) * 60",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  { "title": "Route Emitter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Route Emitter - Sync Duration",
   "type": "graph",
   "description": "Time in ns that the active Route Emitter took to perform its synchronization pass.\n\nUse: Increases in this metric indicate that the Route Emitter may have trouble maintaining an accurate routing table to broadcast to the Gorouters. Tune alerting values to your deployment based on historical data and adjust based on observations over time. The suggested starting point is ≥ 5 for the yellow threshold and ≥ 10 for the critical threshold.\n\nOrigin: Firehose\nType: Gauge (Float in ns)\nFrequency: 60s",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(RouteEmitterSyncDuration{source_id=\"route_emitter\", deployment=~\"$deployment\"}[15m]) / 1000000000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  { "title": "Locket", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Locket - Active Locks",
   "type": "graph",
   "description": "Total count of how many locks the system components are holding.\n\nUse: If the ActiveLocks count is not equal to the expected value, there is likely a problem with Diego.\n\nOrigin: Firehose\nType: Gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(ActiveLocks{source_id=\"locket\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Locket - Active Presences",
   "type": "graph",
   "description": "Total count of active presences. Presences are defined as the registration records that the cells maintain to advertise themselves to the platform.\n\nUse: If the Active Presences count is far from the expected, there might be a problem with Diego.\n\nThe number of active presences varies according to the number of cells deployed. Therefore, during purposeful scale adjustments, this alerting threshold should be adjusted.\nEstablish an initial threshold by observing the historical trends for the deployment over a brief period of time, Increase the threshold as more cells are deployed. During a rolling deploy, this metric shows variance during the BOSH lifecycle when cells are evacuated and restarted. Tolerable variance is within the bounds of the BOSH max inflight range for the instance group.\n\nOrigin: Firehose\nType: Gauge\nFrequency: 60s",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(ActivePresences{source_id=\"locket\", deployment=~\"$deployment\"}[15m])",
     "legendFormat": "{{ip}}"
    }
   ]
  }
 ]
}