{
 "title": "Doppler",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(total_requests{source_id=\"gorouter\"}, deployment)"
   }
  ]
 },
 "panels": [
  { "title": "Loggregator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Transport Loss Rate",
   "type": "graph",
   "description": "Excessive dropped messages can indicate the Dopplers and/or Traffic\nControllers are not processing messages fast enough.\n\nThe recommended scaling indicator is to look at the total dropped as a\npercentage of the total throughput and scale if the derived loss rate\nvalue grows greater than `0.01`.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*sum(rate(dropped{source_id=\"doppler\",direction=\"ingress\", deployment=~\"$deployment\"}[5m])) by (index) / sum(rate(ingress{source_id=\"doppler\", deployment=~\"$deployment\"}[5m])) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Doppler Message Rate Capacity",
   "type": "graph",
   "description": "The recommended scaling indicator is to look at the average load on the\nDoppler instances, and increase the number of Doppler instances when the\nderived rate is 16,000 envelopes per second, or 1 million envelopes per\nminute.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ingress{source_id=\"doppler\", deployment=~\"$deployment\"}[5m])",
     "legendFormat": "{{index}}/{{ip}}"
    }
   ]
  },
  {
   "title": "Reverse Log Proxy Loss Rate",
   "type": "graph",
   "description": "Excessive dropped messages can indicate that the RLP is overloaded and\nthat the Traffic Controllers need to be scaled.\n\nThe recommended scaling indicator is to look at the maximum per minute\nloss rate over a 5-minute window and scale if the derived loss rate\nvalue grows greater than `0.1`.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100*sum(rate(dropped{source_id=\"reverse_log_proxy\", deployment=~\"$deployment\"}[5m])) by (index) / sum(rate(ingress{source_id=\"reverse_log_proxy\"}[5m])) by (index)",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}