{
 "title": "Routing",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "deployment",
    "label": "Deployment",
    "query": "label_values(total_requests{source_id=\"gorouter\"}, deployment)"
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput by Router",
   "type": "graph",
   "description": "The lifetime number of requests completed by the Gorouter VM, emitted per Gorouter instance\n\n**Use**: The aggregation of these values across all Gorouters provide insight into the overall traffic flow of\na deployment. Unusually high spikes, if not known to be associated with an expected increase in demand, could\nindicate a DDoS risk. For performance and capacity management, consider this metric a measure of router\nthroughput per job, converting it to requests-per-second, by looking at the delta value of\n`gorouter.total_requests` and deriving back to 1s, or `(gorouter.total_requests.delta)/5`, per Gorouter instance.\n This helps you see trends in the throughput rate that indicate a need to scale the Gorouter instances. Use the\n trends you observe to tune the threshold alerts for this metric.\n\n**Origin**: Firehose\n**Type**: Counter (Integer)\n**Frequency**: 5s",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_requests{source_id=\"gorouter\", deployment=~\"$deployment\"}[1m])*60",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Latency by Router",
   "type": "graph",
   "description": "The time in milliseconds that the Gorouter takes to handle requests to backend endpoints, which include both\napplications routable platform system APIs like Cloud Controller and UAA. This is the average round trip\nresponse time, which includes router handling.\n\n**Use**: Indicates how Gorouter jobs in PAS are impacting overall responsiveness. Latencies above 100 ms can\nindicate problems with the network, misbehaving backends, or the need to scale the Gorouter itself due to\nongoing traffic congestion. An alert value on this metric should be tuned to the specifics of the deployment\nand its underlying network considerations; a suggested starting point is 100 ms.\n\n**Origin**: Firehose\n**Type**: Gauge (Float in ms)\n**Frequency**: Emitted per Gorouter request, emission should be constant on a running deployment",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.95, latency{source_id=\"gorouter\", deployment=~\"$deployment\"}[1m])",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "502 Bad Gateways by Router",
   "type": "graph",
   "description": "The lifetime number of bad gateways, or 502 responses, from the Gorouter itself, emitted per Gorouter instance.\nThe Gorouter emits a 502 bad gateway error when it has a route in the routing table and, in attempting to make\na connection to the backend, finds that the backend does not exist.\n\n**Use**: Indicates that route tables might be stale. Stale routing tables suggest an issue in the route\nregister management plane, which indicates that something has likely changed with the locations of the\ncontainers. Always investigate unexpected increases in this metric.\n\n**Origin**: Firehose\n**Type**: Count (Integer, Lifetime)\n**Frequency**: 5 s",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bad_gateways{source_id=\"gorouter\", deployment=~\"$deployment\"}[1m])*60",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "All 5XX Errors by Router",
   "type": "graph",
   "description": "The lifetime number of requests completed by the Gorouter VM for HTTP status family 5xx, server errors, emitted\nper Gorouter instance.\n\n**Use**: A repeatedly crashing app is often the cause of a big increase in 5xx responses. However, response\nissues from apps can also cause an increase in 5xx responses. Always investigate an unexpected increase in this\nmetric.\n\n**Origin**: Firehose\n**Type**: Counter (Integer)\n**Frequency**: 5 s",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(responses_5xx{source_id=\"gorouter\", deployment=~\"$deployment\"}[1m])*60",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  { "title": "Router Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Number of Routes Registered by Router",
   "type": "graph",
   "description": "The current total number of routes registered with the Gorouter, emitted per Gorouter instance\n\n**Use**: The aggregation of these values across all Gorouters indicates uptake and gives a picture of the overall growth of the environment for capacity planning.\n\nIt's also recommended alerting on this metric if the number of routes falls outside of the normal range for your deployment. Dramatic decreases in this metric volume may indicate a problem with the route registration process, such as an app outage, or that something in the route register management plane has failed.\n\nIf visualizing these metrics on a dashboard, `gorouter.total_routes` can be helpful for visualizing dramatic drops. However, for alerting purposes, the `gorouter.ms_since_last_registry_update metric` is more valuable for quicker identification of Gorouter issues. Alerting thresholds for `gorouter.total_routes` should focus on dramatic increases or decreases out of expected range.\n\n**Origin**: Firehose\n**Type**: Gauge (Float)\n**Frequency**: 30 s",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "total_routes{source_id=\"gorouter\", deployment=~\"$deployment\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Router File Descriptors By Router",
   "type": "graph",
   "description": "The number of file descriptors currently used by the Gorouter job.\n\n**Use**: Indicates an impending issue with the Gorouter. Without proper mitigation, it is possible for an unresponsive app to eventually exhaust available Gorouter file descriptors and cause route starvation for other apps running on PAS. Under heavy load, this unmitigated situation can also result in the Gorouter losing its connection to NATS and all routes being pruned.\n\nWhile a drop in `gorouter.total_routes` or an increase in `gorouter.ms_since_last_registry_update` helps to surface that the issue may already be occurring, alerting on `gorouter.file_descriptors` indicates that such an issue is impending.\n\nThe Gorouter limits the number of file descriptors to 100,000 per job. Once the limit is met, the Gorouter is unable to establish any new connections.\n\nTo reduce the risk of DDoS attacks, we recommend doing one or both of the following:\n\n* Within PAS, set **Max Connections Per Backend** to define how many requests can be routed to any particular app instance. This prevents a single app from using all Gorouter connections. The value specified should be determined by the operator based on the use cases for that foundation.\n* Add rate limiting at the load balancer level.\n\n**Origin**: Firehose\n**Type**: Gauge\n**Frequency**: 5 s",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "file_descriptors{source_id=\"gorouter\", deployment=~\"$deployment\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Router Exhausted Connections By Router",
   "type": "graph",
   "description": "The lifetime number of requests that have been rejected by the Gorouter VM due to the `Max Connections Per Backend` limit being reached across all tried backends. The limit controls the number of concurrent TCP connections to any particular app instance and is configured within PAS.\n\n**Use**: Indicates that PAS is mitigating risk to other applications by self-protecting the platform against one or more unresponsive applications. Increases in this metric indicate the need to investigate and resolve issues with potentially unresponsive applications. A rapid rate of change upward is concerning and should be assessed further.\n\n**Origin**: Firehose\n**Type**: Counter (Integer)\n**Frequency**: 5 s",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(backend_exhausted_conns{source_id=\"gorouter\", deployment=~\"$deployment\"}[1m])*60",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Time Since Last Route Registered by Router",
   "type": "graph",
   "description": "Time in milliseconds since the last route register was received, emitted per Gorouter instance\n\n**Use**: Indicates if routes are not being registered to apps correctly.\n\n**Origin**: Firehose\n**Type**: Gauge (Float in ms)\n**Frequency**: 30 s",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(ms_since_last_registry_update{source_id=\"gorouter\", deployment=~\"$deployment\"}[1m])/1000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Number of Route Registration Messages Sent and Received",
   "type": "graph",
   "description": "This KPI is based on the following metrics:\n\n* `route_emitter.HTTPRouteNATSMessagesEmitted` reports the lifetime number of route registration messages sent by the Route Emitter component. The metric is emitted for each Route Emitter.\n* `gorouter.registry_message.route-emitter` reports the lifetime number of route registration messages received by the Gorouter. The metric is emitted for each Gorouter instance.\n\nDynamic configuration that enables the Gorouter to route HTTP requests to apps is published by the Route Emitter component colocated on each Diego cell to the NATS clustered message bus. All router instances subscribed to this message bus receive the same configuration. (Router instances within an isolation segment receive configuration only for cells in the same isolation segment.)\n\nAs Gorouters prune app instances from the route when a TTL expires, each Route Emitter periodically publishes the routing configuration for the app instances on the same cell.\n\nTherefore, the aggregate number of route registration messages published by all the Route Emitters should be equal to the number of messages received by each Gorouter instance.\n\n**Use**: A difference in the rate of change of these metrics is an indication of an issue in the control plane responsible for updating the routers with changes to the routing table.\n\nIt's recommended alerting when the number of messages received per second for a given router instance falls below the sum of messages emitted per second across all Route Emitters.\n\nIf visualizing these metrics on a dashboard, look for increases in the difference between the rate of messages received and sent. If the number of messages received by a Gorouter instance drops below the sum of messages sent by the Route Emitters, this is an indication of a problem in the control plane.\n\n**Origin**: Firehose\n**Type**: Counter\n**Frequency**: With each event",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "scalar(sum(rate(HTTPRouteNATSMessagesEmitted{source_id=\"route_emitter\", deployment=~\"$deployment\"}[2m] offset 1m)) * 60) - rate(registry_message_route_emitter{source_id=\"gorouter\"}[2m]) * 60",
     "legendFormat": "{{ip}}"
    }
   ]
  }
 ]
}